/*  =========================================================================
    il_fid_list - List of FILE descriptors for il_log output.

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of the IterationLogger library.                  
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef IL_FID_LIST_H_INCLUDED
#define IL_FID_LIST_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/il_fid_list.api" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef IL_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Constructor.
IL_PRIVATE il_fid_list_t *
    il_fid_list_new (void);

//  *** Draft method, for development use, may change without warning ***
//  Destructor.
IL_PRIVATE void
    il_fid_list_destroy (il_fid_list_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Add file descriptor to list.
IL_PRIVATE void
    il_fid_list_add (il_fid_list_t *self, FILE *fid);

//  *** Draft method, for development use, may change without warning ***
//  Remove file descriptor from list.
IL_PRIVATE void
    il_fid_list_remove (il_fid_list_t *self, FILE *fid);

//  *** Draft method, for development use, may change without warning ***
//  Print formatted string with variable argument list to all FILE descriptors in list.
IL_PRIVATE void
    il_fid_list_printf (il_fid_list_t *self, const char *format, ...) CHECK_PRINTF (2);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
IL_PRIVATE void
    il_fid_list_test (bool verbose);

#endif // IL_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
